### PR TITLE
Remove lists, groups and messages modules from core

### PR DESCRIPTION
**Pull request by FilipNest**
Lists is old, out of date and in need of a big rewrite (should be in contrib when it makes it as could be a big project in itself).

Groups and messages are for the Drupal chat project and should be contrib.

### CODE REVIEW

**Comment by adam-clarey** [comment]
Groups and messages aren't ready to be removed. They need to stay in until we are ready to start publishing contribute modules and we are not there yet. Removing these modules are not necessary at the min and still being used.

**Comment by FilipNest** [comment]
I'm hopefully going to push a contrib module or two to npm this week and I'm sure we'll get lots of others so it'll be good to start pulling stuff out.

Groups and messages in particular are confusing as they don't really offer any functionality out of the box and aren't being used outside of the chat project. I suppose you could write a tutorial for them and put the descriptions in the module files or rename them somehow? 

This request can stay hovering and open until it's ready.

**Comment by adam-clarey** [comment]
I'm happy for it to hang here and will go through soon enough it's just convenient to stay there until we complete the chat functionality etc. Ideally it won't just be for external sites but something that could be used out of the on iris sites. It just needs some client side code adding which can be copied from Drupal stuff.

**Comment by adam-clarey** [comment]
I think there are more pressing issues to pick up in trello for the time being

**Comment by FilipNest** [comment]
Closing as I'm going to make a different pull request for this (code has changed a lot and we know have a better plan for which modules to exclude)

**Pull request closed without merging**
